// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using educationalEcommerce.Server.Infrastructure;

#nullable disable

namespace educationalEcommerce.Server.Migrations
{
    [DbContext(typeof(EduCommDbContext))]
    [Migration("20241005135814_TryEntitesForMapping")]
    partial class TryEntitesForMapping
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("educationalEcommerce.Server.Domain.Entities.Cart", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("educationalEcommerce.Server.Domain.Entities.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CartId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("educationalEcommerce.Server.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("educationalEcommerce.Server.Domain.TryEntities.MainMod", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MainMods");
                });

            modelBuilder.Entity("educationalEcommerce.Server.Domain.TryEntities.ModAlt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("MainModId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MainModId");

                    b.ToTable("ModAlts");
                });

            modelBuilder.Entity("educationalEcommerce.Server.Domain.TryEntities.ModAltItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ModAltId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("ModAltId");

                    b.ToTable("ModAltItems");
                });

            modelBuilder.Entity("educationalEcommerce.Server.Domain.TryEntities.ModIncDec", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("MainModId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MainModId");

                    b.ToTable("ModIncDecs");
                });

            modelBuilder.Entity("educationalEcommerce.Server.Domain.TryEntities.ModIncDecItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ModIncDecId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("ModIncDecId");

                    b.ToTable("ModIncDecItems");
                });

            modelBuilder.Entity("educationalEcommerce.Server.Domain.Entities.Cart", b =>
                {
                    b.HasOne("educationalEcommerce.Server.Domain.Entities.User", "User")
                        .WithOne("Cart")
                        .HasForeignKey("educationalEcommerce.Server.Domain.Entities.Cart", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("educationalEcommerce.Server.Domain.Entities.Item", b =>
                {
                    b.HasOne("educationalEcommerce.Server.Domain.Entities.Cart", "Cart")
                        .WithMany("Items")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cart");
                });

            modelBuilder.Entity("educationalEcommerce.Server.Domain.TryEntities.ModAlt", b =>
                {
                    b.HasOne("educationalEcommerce.Server.Domain.TryEntities.MainMod", "MainMod")
                        .WithMany("ModAlts")
                        .HasForeignKey("MainModId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MainMod");
                });

            modelBuilder.Entity("educationalEcommerce.Server.Domain.TryEntities.ModAltItem", b =>
                {
                    b.HasOne("educationalEcommerce.Server.Domain.TryEntities.ModAlt", "ModAlt")
                        .WithMany("ModAltItems")
                        .HasForeignKey("ModAltId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ModAlt");
                });

            modelBuilder.Entity("educationalEcommerce.Server.Domain.TryEntities.ModIncDec", b =>
                {
                    b.HasOne("educationalEcommerce.Server.Domain.TryEntities.MainMod", "MainMod")
                        .WithMany("ModIncDecs")
                        .HasForeignKey("MainModId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MainMod");
                });

            modelBuilder.Entity("educationalEcommerce.Server.Domain.TryEntities.ModIncDecItem", b =>
                {
                    b.HasOne("educationalEcommerce.Server.Domain.TryEntities.ModIncDec", "ModIncDec")
                        .WithMany("ModIncDecItems")
                        .HasForeignKey("ModIncDecId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ModIncDec");
                });

            modelBuilder.Entity("educationalEcommerce.Server.Domain.Entities.Cart", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("educationalEcommerce.Server.Domain.Entities.User", b =>
                {
                    b.Navigation("Cart")
                        .IsRequired();
                });

            modelBuilder.Entity("educationalEcommerce.Server.Domain.TryEntities.MainMod", b =>
                {
                    b.Navigation("ModAlts");

                    b.Navigation("ModIncDecs");
                });

            modelBuilder.Entity("educationalEcommerce.Server.Domain.TryEntities.ModAlt", b =>
                {
                    b.Navigation("ModAltItems");
                });

            modelBuilder.Entity("educationalEcommerce.Server.Domain.TryEntities.ModIncDec", b =>
                {
                    b.Navigation("ModIncDecItems");
                });
#pragma warning restore 612, 618
        }
    }
}
